es:
  id: ${ES_ID}
  password: ${ES_PASSWORD}
  endpoint: ${ES_ENDPOINT}

general:
  user-agent: ${USER_AGENT}

#logging:
#  level:
#    org:
#      springframework:
#        data:
#          elasticsearch:
#            core: DEBUG
#      elasticsearch:
#        client: TRACE
#      apache:
#        http: TRACE